export const data = [
    {
        "id":"1",
        "time":"20:00",
        "type":"time",
    },
    {
        "id":"2",
        "time":"20:15",
        "type":"time",
    },
    {
        "id":"3",
        "time":"20:30",
        "type":"time",
    },
    {
        "id":"4",
        "time":"20:45",
        "type":"time",
    },
    {
        "id":"5",
        "time":"21:00",
        "type":"time",
    },
    {
        "id":"6",
        "time":"21:15",
        "type":"time",
    },
    {
        "id":"7",
        "time":"21:30",
        "type":"time",
    },
    {
        "id":"8",
        "time":"21:45",
        "type":"time",
    },
    {
        "id":"9",
        "time":"22:00",
        "type":"time",
    },
    {
        "id":"10",
        "time":"22:15",
        "type":"time",
    },
    {
        "id":"11",
        "time":"22:30",
        "type":"time",
    },
    {
        "id":"12",
        "time":"22:45",
        "type":"time",
    },
    {
        "id":"13",
        "time":"23:00",
        "type":"time",
    },
    {
        "id":"14",
        "time":"23:15",
        "type":"time",
    },
    {
        "id":"15",
        "time":"23:30",
        "type":"time",
    },
    {
        "id":"16",
        "time":"23:45",
        "type":"time",
    },
    {
        "id":"17",
        "time":"00:00",
        "type":"time",
    },
    {
        "id":"18",
        "time":"00:15",
        "type":"time",
    },
    {
        "id":"19",
        "time":"00:30",
        "type":"time",
    },
    {
        "id":"20",
        "time":"00:45",
        "type":"time",
    },
    {
        "id":"21",
        "time":"01:00",
        "type":"time",
    },
    {
        "id":"22",
        "time":"01:15",
        "type":"time",
    },
    {
        "id":"23",
        "time":"01:30",
        "type":"time",
    },
    {
        "id":"24",
        "time":"01:45",
        "type":"time",
    },
    {
        "id":"25",
        "time":"02:00",
        "type":"time",
    },
    {
        "id": "26",
        "guests":"1",
        "type":"guest_vol"
    },
    {
        "id": "27",
        "guests":"2",
        "type":"guest_vol"
    },
    {
        "id": "28",
        "guests":"3",
        "type":"guest_vol"
    },
    {
        "id": "29",
        "guests":"4",
        "type":"guest_vol"
    },
]